### ISSUE TITLE
Async notification tests are flaky

### ISSUE THREAD

**Issue by koddsson** [cloudflare/cf-ui#197]
After #196 there seem to be some more tests failing. 

<summary>
Here's the output from my machine
<details>

```
Summary of all failing tests
 FAIL  packages/cf-component-notifications/test/Notification.js (14.283s)
  ● should pause the timeout while the mouse is hovering the notification

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)

  ● should close on click

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

      at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)

```

</details>
</summary>

**Comment by tajo** [comment]
That's strange. The notification is a flaky test. Not sure about the rest. Fela is pinned, that should not be the cause.

**Comment by koddsson** [comment]
I don't think this is a issue any more for whatever reason.
